global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Application Spring Boot
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eventsproject-app:8089']
    scrape_interval: 10s
    labels:
      project: 'projet-devops'
      service: 'backend'

  # cAdvisor pour les métriques des conteneurs
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['eventsproject-cadvisor:8080']
    labels:
      service: 'container-metrics'

  # Node Exporter pour les métriques de l'hôte
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['eventsproject-node-exporter:9100']
    labels:
      service: 'host-metrics'
