global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['eventsproject-app:8089']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['eventsproject-cadvisor:8080']
        labels:
          service: 'container-metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['eventsproject-node-exporter:9100']
        labels:
          service: 'host-metrics'
